version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./client-module
    ports:
      - "8080:8080"
    networks:
      - default
      - app-tier

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: on-failure
    ports:
      - "9090:9090"
    networks:
      - app-tier
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge